const $=id=>document.getElementById(id);let paused=false,selected='',market='',manualMarket=false;
const names={BUY:'买入',SELL:'卖出',HOLD:'观望'};
function fmt(v,n=3){return Number.isFinite(v)?Number(v).toFixed(n):'—'}
function clock(zone){const p=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:zone,weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts().filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return{day:p.weekday,minute:+p.hour*60+(+p.minute)}}
function open(c,ranges){return!['Sat','Sun'].includes(c.day)&&ranges.some(([a,b])=>c.minute>=a&&c.minute<b)}
function defaultMarket(){const hk=clock('Asia/Hong_Kong'),us=clock('America/New_York');if(open(hk,[[570,720],[780,960]]))return'HK';if(open(us,[[570,960]]))return'US';return hk.minute>=480&&hk.minute<1020?'HK':'US'}
function setMarket(value,manual=false){market=value;manualMarket=manual;selected='';document.querySelectorAll('.market-tab').forEach(b=>b.classList.toggle('active',b.dataset.market===market));$('marketHint').textContent=manual?'手动选择':'已按交易时段自动选择'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(v,c){return Number.isFinite(v)?`${c||''} ${Number(v).toLocaleString(undefined,{maximumFractionDigits:2})}`:'—'}
function pct(v){return Number.isFinite(v)?`${v>=0?'+':''}${(v*100).toFixed(2)}%`:'—'}
function renderAccount(accounts){const a=(accounts||{}).HK||(accounts||{}).US;if(!a){$('accountProvider').textContent='等待账户数据';$('accountEquity').textContent=$('accountCash').textContent=$('accountBuyingPower').textContent=$('positionCount').textContent='—';$('positions').innerHTML='<span>正在读取长桥模拟账户……</span>';return}if(a.status==='error'){$('accountProvider').textContent='长桥账户尚未读取成功 · 自动重试中';$('accountEquity').textContent=$('accountCash').textContent=$('accountBuyingPower').textContent=$('positionCount').textContent='—';$('positions').textContent=a.error||'稍后自动重试';return}const stale=a.status==='stale',quotes=a.valuation_status==='ok';$('accountProvider').textContent=`${a.provider} · ${a.currency}${stale?' · 上次成功数据/重试中':quotes?' · 实时只读':' · 持仓报价重试中'}`;$('accountEquity').textContent=money(a.equity,a.currency);$('accountCash').textContent=money(a.cash,a.currency);$('accountBuyingPower').textContent=money(a.buying_power,a.currency);const all=a.positions||[];$('positionCount').textContent=String(all.length);$('positions').innerHTML=all.length?all.map(x=>{const holdClass=Number.isFinite(x.unrealized_pl)?(x.unrealized_pl>=0?'positive':'negative'):'';const dayClass=Number.isFinite(x.today_pl)?(x.today_pl>=0?'positive':'negative'):'';return`<div class="position-row"><div class="position-head"><b>${esc(x.symbol)} ${esc(x.name||'')}</b><span class="market-badge">${esc(x.market||'')}</span></div><div class="position-detail"><span>数量 ${fmt(x.quantity,2)}</span><span>持仓占比 ${pct(x.position_weight)}</span></div><div class="position-detail"><span>现价 ${money(x.current_price,x.currency)}</span><span>成本 ${money(x.cost_price,x.currency)}</span></div><div class="position-detail"><span>市值 ${money(x.market_value,x.currency)}</span><span class="${dayClass}">当日 ${money(x.today_pl,x.currency)} · ${pct(x.today_pl_ratio)}</span></div><div class="position-pl ${holdClass}"><span>持仓盈亏</span><span>${money(x.unrealized_pl,x.currency)} · ${pct(x.unrealized_pl_ratio)}</span></div></div>`}).join(''):'<span>暂无持仓</span>'}
function draw(series){const c=$('scoreChart'),d=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*d;c.height=h*d;const x=c.getContext('2d');x.scale(d,d);x.clearRect(0,0,w,h);x.strokeStyle='#243b35';[.2,.5,.8].forEach(p=>{x.beginPath();x.moveTo(0,h*p);x.lineTo(w,h*p);x.stroke()});if(series.length<2)return;const values=series.flatMap(p=>[p.raw_score||0,p.smooth_score||0]),max=Math.max(25,...values.map(Math.abs));const plot=(key,color)=>{x.strokeStyle=color;x.lineWidth=2;x.beginPath();series.forEach((p,i)=>{const px=i/(series.length-1)*w,py=h/2-(p[key]||0)/max*h*.43;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()};plot('raw_score','#486a60');plot('smooth_score','#66e3c4')}
async function refresh(){try{const r=await fetch('/api/state'),s=await r.json(),all=s.assets||{};if(!market)setMarket(defaultMarket());const assets=Object.fromEntries(Object.entries(all).filter(([symbol,a])=>(a.market||(symbol.endsWith('.HK')?'HK':'US'))===market));if(!selected||!assets[selected])selected=Object.keys(assets)[0]||'';const v=assets[selected]||{market};paused=!!s.latest.paused;$('connection').textContent=paused?'已暂停':'实时运行';$('pause').textContent=paused?'继续实验':'暂停实验';$('signal').textContent=names[v.stable_action]||'观望';$('signal').className=(v.stable_action||'HOLD').toLowerCase();$('source').textContent=`${v.symbol||'等待行情'} / ${v.source_name||market}`;$('price').textContent=fmt(v.price,4);const age=Number.isFinite(v.quote_received_at_ms)?(Date.now()-v.quote_received_at_ms)/1000:v.quote_age_s;$('age').textContent=Number.isFinite(age)?`${fmt(Math.max(0,age),1)} 秒`:'—';$('rawAction').textContent=names[v.raw_action]||'—';$('rawScore').textContent=fmt(v.raw_score);$('smoothScore').textContent=fmt(v.smooth_score);$('windowMean').textContent=fmt(v.window_mean_score);$('enterThreshold').textContent=fmt(v.enter_threshold);$('triggerDistance').textContent=fmt(v.distance_to_trigger);$('calibration').textContent=v.calibration_status==='ready'?`已完成 · ${v.baseline_samples||0}样本`:`预热中 · 剩余${fmt(v.warmup_remaining_s,0)}秒`;$('stimulus').textContent=Number.isFinite(v.stimulus_scale)?`${fmt(v.stimulus_scale*100,0)}%`:'—';$('steps').textContent=(v.model_step||0).toLocaleString();$('assets').innerHTML=Object.values(assets).map(a=>`<div class="asset ${a.symbol===selected?'active':''}" data-symbol="${a.symbol}"><b>${a.symbol}</b><em class="${(a.stable_action||'HOLD').toLowerCase()}">${names[a.stable_action]||'观望'}</em><span>${fmt(a.price,2)}</span></div>`).join('');document.querySelectorAll('.asset').forEach(e=>e.onclick=()=>{selected=e.dataset.symbol;refresh()});draw((s.series||[]).filter(p=>p.symbol===selected))}catch(e){$('connection').textContent='连接断开'}}
async function refreshAccount(){try{const r=await fetch('/api/state'),s=await r.json();renderAccount(s.accounts)}catch(e){$('accountProvider').textContent='账户连接断开'}}
async function refreshProposal(){try{const r=await fetch('/api/state'),s=await r.json(),p=(s.proposals||{})[selected];if(!p){$('proposalStatus').textContent='等待行情与稳定信号';$('riskChecks').innerHTML='<span>等待风控检查</span>';return}const action={BUY:'买入',SELL:'卖出',HOLD:'观望'}[p.action]||p.action;$('proposalAction').textContent=action;$('proposalQuantity').textContent=fmt(p.quantity,0);$('proposalPrice').textContent=fmt(p.reference_price,3);$('proposalReason').textContent=p.reason||'—';const status={ready:'允许提案',blocked:'已拦截',confirming:'确认中',observing:'观察中'}[p.status]||p.status;$('proposalStatus').textContent=`${status} · 仅预演`;$('proposalStatus').className=`proposal-${p.status}`;const icons={passed:'✓',blocked:'×',confirming:'…',observing:'…',skipped:'–',pending:'·'};$('riskChecks').innerHTML=(p.risk_checks||[]).map(c=>`<span class="risk-${esc(c.status)}" title="${esc(c.reason)}">${icons[c.status]||'·'} ${esc(c.label)}</span>`).join('')||'<span>暂无风控明细</span>'}catch(e){$('proposalStatus').textContent='提案状态暂不可用'}}
document.querySelectorAll('.market-tab').forEach(b=>b.onclick=()=>{setMarket(b.dataset.market,true);refresh()});$('pause').onclick=async()=>{await fetch('/api/pause',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({paused:!paused})});refresh()};setMarket(defaultMarket());setInterval(refresh,500);refresh();
setInterval(refreshAccount,1000);refreshAccount();
setInterval(refreshProposal,500);refreshProposal();
async function refreshHealth(){try{const r=await fetch('/api/state'),s=await r.json(),v=(s.assets||{})[selected]||{},h=v.runtime_health||{};$('eventHealth').textContent=Number.isFinite(h.received_events)?`${h.received_events} / ${h.accepted_events}`:'—';$('dropHealth').textContent=Number.isFinite(h.dropped_queue_events)?`${h.dropped_queue_events} / ${h.duplicate_or_old_events}`:'—';$('latencyHealth').textContent=Number.isFinite(h.max_tick_latency_ms)?`${fmt(h.max_tick_latency_ms,1)} ms`:'—'}catch(e){$('eventHealth').textContent='—'}}
setInterval(refreshHealth,1000);refreshHealth();
async function refreshTracks(){try{const r=await fetch('/api/state'),s=await r.json(),v=(s.assets||{})[selected]||{},p=(s.proposals||{})[selected]||{};const raw=v.raw_action||'HOLD',ex=p.status==='ready'?(p.side||'HOLD'):'HOLD';$('rawTrack').textContent=names[raw]||raw;$('rawTrack').className=raw.toLowerCase();$('executableTrack').textContent=names[ex]||ex;$('executableTrack').className=ex.toLowerCase()}catch(e){$('rawTrack').textContent='—';$('executableTrack').textContent='—'}}
setInterval(refreshTracks,500);refreshTracks();
async function refreshPerformance(){try{const r=await fetch('/api/state'),s=await r.json(),p=(s.performance||{})[selected];if(!p){$('performanceMeta').textContent='等待第一条实验事件';$('performanceRows').innerHTML='<span>暂无数据</span>';return}$('performanceMeta').textContent=p.points+' 个决策点 · 本次进程';const order=['fly_raw','fly_filtered','risk_executable','buy_and_hold','disconnected_connectome'];$('performanceRows').innerHTML=order.map(k=>{const x=(p.tracks||{})[k];if(!x)return'';const cls=x.return>0?'positive':x.return<0?'negative':'';return '<div class="performance-row"><strong class="track-label">'+esc(x.label)+'</strong><span class="'+cls+'">'+pct(x.return)+'</span><span class="negative">'+pct(x.max_drawdown)+'</span><span>'+x.trades+' / '+x.round_trips+'</span><span>'+(x.holding?'持仓':'空仓')+'</span></div>'}).join('')}catch(e){$('performanceMeta').textContent='收益状态暂不可用'}}
setInterval(refreshPerformance,500);refreshPerformance();
